### ISSUE TITLE
angular cli error

### ISSUE THREAD

**Issue by mkscala** [webmaxru/angularmaterial2-guide-angularcamp#1]
does it support new version on Angular-CLI, it fails with 

$material2-demo mkmani$ ng serve

**It seems like you're using a project generated using an old version of the Angular CLI.
The latest CLI now uses webpack and includes a lot of improvements, include a simpler
workflow, a faster build and smaller bundles.**

To get more info, including a step-by-step guide to upgrade the CLI, follow this link:
https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.12

**Comment by webmaxru** [comment]
Hi! Yes, the demo was built using July's versions of packages. I'm afraid it will be much easier to take the latest Angular 2 quickstart, Angular CLI and Angular Material 2 and implement these simple list and form than try to upgrage the current demo setup. Also you can have a look at this repo: https://github.com/webmaxru/angularmaterial2-guide-javazone It was built using a-week-before-release version, but probably current CLI is OK with this.
